### PR TITLE
New model support: Qwen

### PR DESCRIPTION
**Pull request by Ninot1Quyi**
**Added support for the online Qwen model, enabling the use of Alibaba Cloud's latest model Qwen-max.**
<p align="center">
    
<p>

### CODE REVIEW

**Comment by Ninot1Quyi** [comment]
Support for online Qwen has been completed. There is a certain amount of free credit for new registrations. If changes are needed, I will refer to the suggestions for further changes

**Comment by FantomWolf182** [comment]
Cool I heard Minty from the discord discussing this model. I'll definitely mess around with it soon

**Comment by Ninot1Quyi** [comment]
need more test，and will add tools support.

**Comment by Ninot1Quyi** [comment]
JurassikLizard said he will add a !wiki directive, I think I don't need to add separate networking tools in the api for Qwen at the moment.

**Comment by Ninot1Quyi** [comment]
that's all.If there are bugs I will try to fix the code O.o

**Comment by JurassikLizard** [comment]
> JurassikLizard said he will add a !wiki directive, I think I don't need to add separate networking tools in the api for Qwen at the moment.

Which networking tools where you thinking of using?

**Review by MaxRobinsonTheGreat — APPROVED** [review]
looks good, though I haven't been able to test it because my api key is unauthorized.

**Comment by Ninot1Quyi** [comment]
Sorry, I didn't find any new reply after the PR merger.

**Comment by Ninot1Quyi** [comment]
> looks good, though I haven't been able to test it because my api key is unauthorized.

Sorry, I didn't find any new reply after the PR merger. Did you get Qwen's api key but can't use it? If you want to test, I can provide you with a certain amount of key. I can help you if you want your own key.

**Comment by Ninot1Quyi** [comment]
> > JurassikLizard said he will add a !wiki directive, I think I don't need to add separate networking tools in the api for Qwen at the moment.
> 
> Which networking tools where you thinking of using?
> 
> Edit: Wiki command is working, but I need to finalize it more to be able to have a feature PR.

I was going to join a simple crawler that uses request to crawl wiki pages to get relevant content. Then give qwen the right to use the tool function. But then think about it, this should be like you said add '! wiki 'directive, used for all models. You are right bro.

**Pull request merged**
