### PR TITLE
added o1 support and prompt param to newAction

### PR DESCRIPTION
**Pull request by MaxRobinsonTheGreat**

### CODE REVIEW

**Comment by MCbabel** [comment]
Hi, I've tested it and it doesn't really work well. o1 does what it wants, doesn't respond to any requests or responds very slowly. It also talks to itself and does some things that are in the examples, it also spams in the chat. And does things twice and three times. How can I fix this?

**Comment by MaxRobinsonTheGreat** [comment]
@MCbabel well that was a fast review. Yes I have had similar behavior. Unfortunately the o1 models seem to take different chat strucutres, so they get confused often. But I've been able to use o1-preview with good results, especially for building. Are you using o1-mini?

**Comment by MCbabel** [comment]
Yes, I have used o1-mini. But I can also test o1-preview

**Comment by MaxRobinsonTheGreat** [comment]
I think I made it a bit better. still wonky. I'll improve in the future

**Comment by MCbabel** [comment]
@MaxRobinsonTheGreat That would make me very happy! Thank you very much!

**Pull request merged**
