### PR TITLE
Basic Groq support!

### PR DESCRIPTION
**Pull request by FateUnix29**
Followup to https://github.com/kolbytn/mindcraft/issues/108
I honestly don't know how I pulled it off.
Excuse my poor commit messages as well.
But look! I managed to get mixtral-8x7b-32768 into the game somehow after like one hour of modification.
image
I once thought of this PR being messy and not suitable for merge, and while it could probably be improved in a few areas, it's actually in a really good state code-wise. Some of the models are less than sane though.

### CODE REVIEW

**Comment by FateUnix29** [comment]
https://github.com/kolbytn/mindcraft/issues/108#issue-2354586229

**Comment by FateUnix29** [comment]
It seems to be responding to it's own examples. I'll look into it.

**Comment by FateUnix29** [comment]
Yeah no. That was weird. Theres no problem. This seems like it only happened a few times.

**Comment by FateUnix29** [comment]
UPDATE: it's just reading its own stats, inventory, etc and responding

**Comment by FateUnix29** [comment]
I just pushed a new system prompt. Before pushing, I tested it, and it almost worked. It pretended to use a command though. I think I fixed that.

**Comment by FateUnix29** [comment]
it REALLY seems to hate newAction.

**Comment by FateUnix29** [comment]
it no longer seems to hate newAction.

**Comment by FIREBALL252423** [comment]
What have I done incorrectly? In the console there is a message which says that the embedding for groq wasn't found and an "read ECONNRESET" error.

**Comment by FateUnix29** [comment]
Actually, I'm not too sure.
Did you provide your Groq API key?

**Comment by FateUnix29** [comment]
"read ECONNRESET" sounds like an internal error that MindCraft may raise.

**Comment by FateUnix29** [comment]
For now, I recommend you use MindCraft as is... I may investigate, but ultimately, I've been done with this for a while now.

**Comment by FIREBALL252423** [comment]
Yes I did provide the api but I am not very experienced with repositories and I am sure I forgot to change something in the files. Can you update the README.md?

**Comment by FateUnix29** [comment]
hmm... all of the files that were changed should've been included within my fork.

**Comment by FateUnix29** [comment]
Look, as much as I want to help you, I've moved on. This was a .. Rather sloppy modification of MindCraft (probably, at least) that wasn't fully bug-tested.
I don't even really know what I changed anymore, and I'm doing other stuff now.

**Comment by FateUnix29** [comment]
In `settings.js`, make sure that the selected profile is ./profiles/dolphin.json

**Comment by FateUnix29** [comment]
I hope whatever was in the changes helps.

**Comment by FIREBALL252423** [comment]
I found out the problem is it can't join a server if provided with the domain name instead of the numerical ip. That's very odd because it worked when I used mindcraft.

**Comment by FateUnix29** [comment]
Oh... Yeah. No. This was never intended to be on a server. That more sounds like a MindCraft issue.
It should work just fine if you open your world to LAN, but MindCraft doesn't really seem like it's meant to be used on servers just yet...

**Comment by FateUnix29** [comment]
For that, are you also sure that your config file says to authenticate with Minecraft, that it has it's own account, or you have it set up to use your own with you, yada yada

**Comment by FantomWolf182** [comment]
yo im trying to add gemma2-9b-it but keep getting this error:

message: "max_tokens must be less than the model's sequence length (8192)",

do you know how to fix it?

**Comment by FateUnix29** [comment]
it should be somewhere in the .json you declared.
look at `dolphin.json`, it should have a max tokens thing
maybe
i dunno
if not, you may have to go into .. `groq.js`? if it exists?
and set max tokens to below 8192. keep doing so until the error no longer shows. i suggest 4096.

**Comment by kolbytn** [comment]
Hey! This looks cool. Can you merge the latest from main into your pr? We just finished a big update.

**Comment by FantomWolf182** [comment]
OFFICIAL GROQ SUPPORT?!

**Comment by MaxRobinsonTheGreat** [comment]
@FateUnix29 Wait, this is not grok from xAI, its just a different api? Mixtral is already supported in the replicate api, and I've found it to be abysmal. Is there any advantage to groq?

**Comment by FantomWolf182** [comment]
GroqAi is mainly free to use even through the API. [link to groqai](https://console.groq.com/login)

**Comment by FateUnix29** [comment]
where did you people come from?
what happened?
i just went through my emails.

**Comment by FateUnix29** [comment]
> Hey! We're taking a look at this. Can you merge the latest from main into your pr? We just finished a big update.

what??
huh??
merge the latest from main into my pr.

**Comment by FateUnix29** [comment]
I have resolved the settings.js conflict, however, I am unsure if the basic functionality of my PR is intact.

**Comment by MaxRobinsonTheGreat** [comment]
> I have resolved the settings.js conflict, however, I am unsure if the basic functionality of my PR is intact.

You can always test it. But again, what's the advantage here? Does it actually work well? Mixtral has been terrible for me

**Comment by FantomWolf182** [comment]
Groq also has other models.

**Comment by FateUnix29** [comment]
> > I have resolved the settings.js conflict, however, I am unsure if the basic functionality of my PR is intact.
> 
> You can always test it. But again, what's the advantage here? Does it actually work well? Mixtral has been terrible for me

Like Fantom said, there are other models. In my personal testing for a chat bot, llama3-70b-8192 seems to be alright. Said model was also able to play another game given my specific function calls.

**Comment by FateUnix29** [comment]
I'll make sure my PR is up to date and begin adding those models in

**Comment by FateUnix29** [comment]
> yo im trying to add gemma2-9b-it but keep getting this error:
> 
> message: "max_tokens must be less than the model's sequence length (8192)",
> 
> do you know how to fix it?

Oh, this model was never supported, and by default, it uses a 16k sequence length.
I'll add this one too.

**Comment by MaxRobinsonTheGreat** [comment]
> Mindcraft would probably benefit from no longer assuming each service only provides one model, as Groq provides.. 5

It doesn't, the replicate API supports mixtral and llama. Is groq faster/better/cheaper than replicate? I think it would be best to only support one of these APIs.

@FateUnix29 Could you do something similar where there is one Groq class that supports different model names? You can steal from the ReplicateAPI class, and replace it too as the default for llama.

**Comment by FateUnix29** [comment]
I'll check out what I might be able to do.

**Comment by FateUnix29** [comment]
Hey! I'm doing that now.

**Comment by FateUnix29** [comment]
WOAH WOAH WOAH GROQCLOUD HAS A LOT MORE MODELS NOW PANIC PANIC

**Comment by FateUnix29** [comment]
Groq-based profiles now have a "max_tokens" field, as well as now using "groq/" as a prefix due to the massive influx of Groq models.
image
image
max_tokens doesn't need to exist, but if it is specified and the model starts with "groq/" or "groqcloud/", it will be used. Heavily recommended for setting it higher or lower than 8192 depending on a particular mode's limits.

**Comment by FateUnix29** [comment]
WAIT WAIT WAIT WAIT ONE OF THE MODELS IS ONE SPECIFICALLY DESIGNED FOR FUNCTION CALLING

**Comment by FantomWolf182** [comment]
You know what they say: 

No pain, others don't gain from your actions.

Or something like that...

**Comment by FateUnix29** [comment]
yea. llama-3.1-70b-versatile works best

**Comment by FateUnix29** [comment]
along with groq support im going to try and nail some mod block and item support into here

**Comment by FateUnix29** [comment]
I don't think I can. I'm still looking.

**Comment by FantomWolf182** [comment]
> yea. llama-3.1-70b-versatile works best I THINK

Yeah it makes some really cool builds 

I attached a snow globe. image

**Comment by FateUnix29** [comment]
WOW.

> > yea. llama-3.1-70b-versatile works best I THINK
> 
> Yeah it makes some really cool builds
> 
> I attached a snow globe. image

WOW.
I DID NOT EXPECT THAT.

**Comment by FateUnix29** [comment]
It managed to do that?
There's going to be a 400-billion param model soon. Imagine what that thing could do.
I'm so glad I tried to implement this.

**Comment by FateUnix29** [comment]
I'm beginning to really hope this PR gets accepted. Let me check if there are any local changes I may have forgot to push.

**Comment by FantomWolf182** [comment]
Manners commit 💀

**Comment by FateUnix29** [comment]
Meh. Whatever. In Emergent Garden's latest video, he mentions bot-to-bot communication.
I was thinking of it right before he said anything about it.
I once ran seven of these Groq-based models, and noticed they couldn't hear one another. I had to be their bridge.
What if there was a specific character(s) that, upon being used by any entity in chat, would broadcast it to *all* bots?

This is NOT a new idea - My Discord bot has a special character, ^, that you can start your message off with to either exclude it from being sent to the bot or INCLUDE it, in any channel.

An AI I integrated into another game, while being limited to the chat function, used /- to send the message to the bot, no matter who sent it, including itself.

**Comment by FateUnix29** [comment]
image
ouchie

**Comment by FateUnix29** [comment]
image
I got broadcasting half working. I really don't know JavaScript well. I thought that multiple lines of action in an if statement didn't need brackets. Anyhow, this entire conversation happened in about 1 second after revealing to them they could use ^.

**Comment by FateUnix29** [comment]
Oh. Wow. They're still going. Wow.

**Comment by FateUnix29** [comment]
image

**Comment by FateUnix29** [comment]
They were seemingly plotting to make more of themselves before they both crashed due to the nuts amount of talk they were doing.
image

**Comment by FantomWolf182** [comment]
I would say make the broadcasting a different pr

**Comment by FateUnix29** [comment]
Probably. Some time after this PR gets merged. It's designed on top of this one.

**Comment by FateUnix29** [comment]
Went around the issues. Groq talks are actually a lot more common than I thought.

**Comment by MaxRobinsonTheGreat** [comment]
@FateUnix29 I'd like to get this merged in. Is it ready for review?

**Comment by FateUnix29** [comment]
> @FateUnix29 I'd like to get this merged in. Is it ready for review?

I don't think you're a maintainer of this project, unless I'm mistaken...?
If you do indeed have that authority, I would say it's in an alright state. **However.**
I need to get around to removing broadcasting and adding it as it's own separate thing, reviewing *myself*, etc...

**Comment by MaxRobinsonTheGreat** [comment]
lol I am a maintainer, I make the youtube videos. well it would be best to clean it up then. @ me when you want me to review it. I'm eager to support groq, and I might implement it myself

**Comment by FateUnix29** [comment]
> lol I am a maintainer, I make the youtube videos. well it would be best to clean it up then. @ me when you want me to review it. I'm eager to support groq, and I might implement it myself

Ah I see. Yea. I'll get to you on that.

**Comment by MaxRobinsonTheGreat** [comment]
Hey @FateUnix29 , I touched up a few things and merged this in. Thanks for the work, it's great! And the code was in a very good state. I did not realize how fast/free groq is, I wished I'd merged it sooner

**Comment by FateUnix29** [comment]
> Hey @FateUnix29 , I touched up a few things and merged this in. Thanks for the work, it's great! And the code was in a very good state. I did not realize how fast/free groq is, I wished I'd merged it sooner

Sick! I was about to apologize for being late (I was caught up in quite a few other projects. Oh, if only I could focus on one).
This was my first proper PR to ANYWHERE, and it's why in the original post, I doubted myself heavily and told maintainers not to merge it.
This project was also the reason I learned basic JavaScript, just enough to get this running.
I'm glad it works, and that my hard work paid off.

**Pull request merged**
