### PR TITLE
Simple hugging face support (again)

### PR DESCRIPTION
**Pull request by 1223nij**
Made it in a fresh repo without all the groq commits!

### CODE REVIEW

**Comment by FateUnix29** [comment]
Love this, and love the extra step to make sure you aren't merging any deprecated or unused Groq code.

**Comment by FantomWolf182** [comment]
If this is finished maybe ping Maximus on discord because I think this would be useful for a lot of people.

**Comment by MaxRobinsonTheGreat** [comment]
I will review this weekend, sorry for the wait!!

**Comment by FateUnix29** [comment]
Yoo!!! 🎉

**Comment by FateUnix29** [comment]
I look forward to hopefully seeing the Groq and Hugging Face support in future videos.

**Pull request merged**
