### PR TITLE
Method of Groq API Support

### PR DESCRIPTION
**Pull request by 1223nij**
Implemented Groq's API

### CODE REVIEW

**Comment by 1223nij** [comment]
Resolves #176

**Comment by chiro1879** [comment]
I'm not 100% sure if you fixed this or not because I was using it before that last commit, however it is extremely easy to get rate-limited if you do complex tasks

> RateLimitError: 429 {"error":{"message":"Rate limit reached for model `llama3-70b-8192` in organization `[nah]` on tokens per minute (TPM): Limit 6000, Used 5914, Requested 1822. Please try again in 17.359s. Visit https://console.groq.com/docs/rate-limits for more information.","type":"tokens","code":"rate_limit_exceeded"}}

**Comment by FantomWolf182** [comment]
Someone else is already working on this.

**Comment by FantomWolf182** [comment]
https://github.com/kolbytn/mindcraft/pull/115

**Pull request closed without merging**
