### PR TITLE
Fixing various bugs.

### PR DESCRIPTION
**Pull request by BF5258**
Bugs fixed (I hope):
- #185 Early return if resources are not present.
- #187 Check types of all parameters.
- #167 Just a warning but lots of people have asked about it on both GitHub and Discord.
- #190

### CODE REVIEW

**Comment by FateUnix29** [comment]
Someone finally fixed physicsTick. Holy.

**Comment by FantomWolf182** [comment]
How would the armor be equipped automatically? I'm asking because the bot doesn't know when inventory is updated.

**Comment by luiscosio** [comment]
It would be ideal if this got merged @kolbytn

**Comment by MaxRobinsonTheGreat** [comment]
@luiscosio dev here. could you merge with main and resolve conflicts first? I can take a look at it this weekend.

**Comment by BF5258** [comment]
> How would the armor be equipped automatically? I'm asking because the bot doesn't know when inventory is updated.

I was trying to listen for the chat message, but Mineflayer often omits parts.

expected message: `'[BF5258: Gave 1 [Iron Boots] to andy]'`
Mineflayer message: `'[: Gave  [Iron Boots] to andy]'`

```
this.bot.on('messagestr', (message) => {
    const giveCommandRegex = /^(?:\[(?<giver>(?:.+)): )?Gave (?<amount>\d+) \[(?<itemName>[\w ]+)\] to (?<recipient>\w+)\]?$/;
    const match = message.match(giveCommandRegex);
    if(!match || match.groups.recipient!=this.name) return;
    this.bot.armorManager.equipAll();
});
```
Is there a better way to do this?

**Comment by FantomWolf182** [comment]
Found this plugin https://github.com/PrismarineJS/MineflayerArmorManager

**Comment by BF5258** [comment]
> Found this plugin https://github.com/PrismarineJS/MineflayerArmorManager

Although MineflayerArmorManager automatically equips picked up items, it doesn't check for crafting or /give.
 `this.bot.armorManager.equipAll();` tells it to check the inventory for items and equip any that are better.

**Comment by MaxRobinsonTheGreat** [comment]
@BF5258 Thanks for your work on this! The param typing is especially useful. I made a PR with some changes: #219 

The main thing is I removed the blocks.json patch. Seems like the bug you're trying to fix is when it calls `!collectBlock('water',1)`? Instead I prefer the collectblock func to just behave differently for these special blocks, like using a bucket. 
I try to keep patching at a minimum; versioning is already becoming a nightmare. Lmk if there is another reason for the patch.

We can do that in another PR. I will merge mine today.

**Comment by MaxRobinsonTheGreat** [comment]
oh also on the armor manager thing, I am gonna add some modes for autoequipping and autoeating, the plugins seem buggy. it would just periodically call armormanager.equip()

**Comment by MaxRobinsonTheGreat** [comment]
#219 is now merged

**Pull request closed without merging**
