### PR TITLE
 Add option to set custom openai compatible server

### PR DESCRIPTION
**Pull request by bugmaschine**
I tested it with deepseek-chat and it works, should also work with koboldcpp for local models

### CODE REVIEW

**Comment by Felitendo** [comment]
Will it default to the openai URI when nothing is selected?

**Comment by bugmaschine** [comment]
Yes

**Comment by Lorodn4x** [comment]
а зачем это делать если можно просто указать в файле профиля "model": {
  "api": "openai",
  "url": "https://api.openai.com/v1/",
  "model": "gpt-3.5-turbo"
},
"embedding": {
  "api": "openai",
  "url": "https://api.openai.com/v1/",
  "model": "text-embedding-ada-002"
}

image

**Comment by Lorodn4x** [comment]
why do this if you can already specify your own endpoint in the profile file? "model": {
  "api": "openai",
  "url": "https://api.openai.com/v1/",
  "model": "gpt-3.5-turbo"
},
"embedding": {
  "api": "openai",
  "url": "https://api.openai.com/v1/",
  "model": "text-embedding-ada-002"
}

image

**Comment by Lorodn4x** [comment]
why do this if you can already specify your own endpoint in the profile file? "model": {
  "api": "openai",
  "url": "https://api.openai.com/v1/",
  "model": "gpt-3.5-turbo"
},
"embedding": {
  "api": "openai",
  "url": "https://api.openai.com/v1/",
  "model": "text-embedding-ada-002"
}

image

**Comment by bugmaschine** [comment]
because it dosen't work

**Comment by bugmaschine** [comment]
didint notice that to be honest lol

**Comment by Lorodn4x** [comment]
I didn't notice it right away either, but that's how it works. Maybe there are some shortcomings, I don't know. https://youtu.be/rdXqNPnVGiM?si=c85coKtvyS-xE99B

**Pull request closed without merging**
