### PR TITLE
Instruction on how to run the bot in the docker to reduce some of the risks of running unknown code

### PR DESCRIPTION
**Pull request by keneo**
run in docker instruction

### CODE REVIEW

**Comment by keneo** [comment]
@Felitendo Are you sure you want a docker compose? I just run the "docker run -it..." to start and press ctrl-c to stop.

**Comment by JurassikLizard** [comment]
I don't think docker compose is a great idea - since all of the configuration is already handled by the project.
And it also doesn't require multiple containers.
Otherwise this is a cool README addition, I like it.

**Comment by keneo** [comment]
@Felitendo done :)

**Comment by Felitendo** [comment]
> @Felitendo done :)

Nice, could you also add an exposed port so we can access the prismarine viewer?

**Comment by Felitendo** [comment]
> @Felitendo ok, please explain how do you use prismarine viewer currently? I'm not familiar

Take a look at settings.js
There I just turned on "show_bot_views" and went to localhost:3000 or localhost:3001

**Comment by keneo** [comment]
@Felitendo done

**Comment by keneo** [comment]
@Felitendo I added another use case for docker-compose: viaproxy service

**Comment by Felitendo** [comment]
Awesome :)
Thanks for adding ViaProxy btw

**Review by MaxRobinsonTheGreat — APPROVED** [review]
docker hates me, so I haven't tested this, but since there are no code changes I will merge in :) thanks

**Comment by keneo** [comment]
@MaxRobinsonTheGreat thx for the merge :) I can help you with docker if you need. I PM'ed you just now.

**Pull request merged**
